"""add credentials webhooks schedules variables

Revision ID: 246c0daca2a8
Revises: 298683ca3baa
Create Date: 2026-09-08 22:51:02.328176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '246c0daca2a8'
down_revision: Union[str, Sequence[str], None] = '298683ca3baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('encrypted_data', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_dek', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('oauth_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_credentials_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_credentials_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials'))
    )
    op.create_index(op.f('ix_credentials_project_id'), 'credentials', ['project_id'], unique=False)
    op.create_index('uq_credentials_project_name', 'credentials', ['project_id', 'name'], unique=True)
    op.create_table('variables',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('encrypted_value', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_dek', sa.LargeBinary(), nullable=True),
    sa.Column('nonce', sa.LargeBinary(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("key ~ '^[A-Z][A-Z0-9_]*$'", name=op.f('ck_variables_key_screaming_snake_case')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_variables_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_variables_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variables'))
    )
    op.create_index(op.f('ix_variables_organization_id'), 'variables', ['organization_id'], unique=False)
    op.create_index('uq_variables_org_project_key', 'variables', ['organization_id', 'project_id', 'key'], unique=True)
    op.create_table('schedules',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=200), nullable=False),
    sa.Column('cron', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('catch_up', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_schedules_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index('ix_schedules_next_run', 'schedules', ['next_run_at'], unique=False, postgresql_where=sa.text('is_enabled'))
    op.create_index(op.f('ix_schedules_workflow_id'), 'schedules', ['workflow_id'], unique=False)
    op.create_table('webhook_registrations',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=200), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_webhook_registrations_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_registrations'))
    )
    op.create_index(op.f('ix_webhook_registrations_workflow_id'), 'webhook_registrations', ['workflow_id'], unique=False)
    op.create_index('uq_webhook_registrations_path_method_test', 'webhook_registrations', ['path', 'method', 'is_test'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_webhook_registrations_path_method_test', table_name='webhook_registrations')
    op.drop_index(op.f('ix_webhook_registrations_workflow_id'), table_name='webhook_registrations')
    op.drop_table('webhook_registrations')
    op.drop_index(op.f('ix_schedules_workflow_id'), table_name='schedules')
    op.drop_index('ix_schedules_next_run', table_name='schedules', postgresql_where=sa.text('is_enabled'))
    op.drop_table('schedules')
    op.drop_index('uq_variables_org_project_key', table_name='variables')
    op.drop_index(op.f('ix_variables_organization_id'), table_name='variables')
    op.drop_table('variables')
    op.drop_index('uq_credentials_project_name', table_name='credentials')
    op.drop_index(op.f('ix_credentials_project_id'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
