"""add executions node_executions execution_data

Revision ID: 298683ca3baa
Revises: a3301536f147
Create Date: 2026-09-08 12:50:46.689402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '298683ca3baa'
down_revision: Union[str, Sequence[str], None] = 'a3301536f147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_version_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('trigger_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resume_token', sa.String(length=64), nullable=True),
    sa.Column('resume_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_execution_id', sa.Uuid(), nullable=True),
    sa.Column('retry_of_execution_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_executions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_execution_id'], ['executions.id'], name=op.f('fk_executions_parent_execution_id_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_executions_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retry_of_execution_id'], ['executions.id'], name=op.f('fk_executions_retry_of_execution_id_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_executions_workflow_id_workflows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], name=op.f('fk_executions_workflow_version_id_workflow_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions')),
    sa.UniqueConstraint('resume_token', name=op.f('uq_executions_resume_token'))
    )
    op.create_index(op.f('ix_executions_created_at'), 'executions', ['created_at'], unique=False)
    op.create_index('ix_executions_project_created', 'executions', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_executions_project_id'), 'executions', ['project_id'], unique=False)
    op.create_index('ix_executions_status_created', 'executions', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status IN ('queued','running','waiting')"))
    op.create_index('ix_executions_workflow_created', 'executions', ['workflow_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_executions_workflow_id'), 'executions', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_executions_workflow_version_id'), 'executions', ['workflow_version_id'], unique=False)
    op.create_table('execution_data',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('object_key', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_execution_data_execution_id_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_data'))
    )
    op.create_index(op.f('ix_execution_data_execution_id'), 'execution_data', ['execution_id'], unique=False)
    op.create_table('node_executions',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=200), nullable=False),
    sa.Column('node_name', sa.String(length=200), nullable=False),
    sa.Column('node_type', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('run_index', sa.Integer(), nullable=False),
    sa.Column('items_in', sa.Integer(), nullable=True),
    sa.Column('items_out', sa.Integer(), nullable=True),
    sa.Column('input_data_id', sa.Uuid(), nullable=True),
    sa.Column('output_data_id', sa.Uuid(), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_node_executions_execution_id_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['input_data_id'], ['execution_data.id'], name=op.f('fk_node_executions_input_data_id_execution_data'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['output_data_id'], ['execution_data.id'], name=op.f('fk_node_executions_output_data_id_execution_data'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_executions'))
    )
    op.create_index(op.f('ix_node_executions_execution_id'), 'node_executions', ['execution_id'], unique=False)
    op.create_index('uq_node_executions_execution_node_run', 'node_executions', ['execution_id', 'node_id', 'run_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_node_executions_execution_node_run', table_name='node_executions')
    op.drop_index(op.f('ix_node_executions_execution_id'), table_name='node_executions')
    op.drop_table('node_executions')
    op.drop_index(op.f('ix_execution_data_execution_id'), table_name='execution_data')
    op.drop_table('execution_data')
    op.drop_index(op.f('ix_executions_workflow_version_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_workflow_id'), table_name='executions')
    op.drop_index('ix_executions_workflow_created', table_name='executions')
    op.drop_index('ix_executions_status_created', table_name='executions', postgresql_where=sa.text("status IN ('queued','running','waiting')"))
    op.drop_index(op.f('ix_executions_project_id'), table_name='executions')
    op.drop_index('ix_executions_project_created', table_name='executions')
    op.drop_index(op.f('ix_executions_created_at'), table_name='executions')
    op.drop_table('executions')
    # ### end Alembic commands ###
